---
# Initial Server Setup
user: ansible

# MySQL Setup
mysql_root_password: mysql_root_password
mysql_app_db: laravel_db
mysql_app_user: mysql_user
mysql_app_pass: db_password


# Web Server Setup
http_host: "{{ ansible_facts.eth0.ipv4.address }}"
remote_www_root: /var/www
app_root_dir: laravel
document_root: "{{ remote_www_root }}/{{ app_root_dir }}/public"

    

# Laravel Env Variables
app_name: Laravel
app_env: dev
app_debug: true
app_url: "http://{{ http_host }}"
db_host: localhost
db_port: 3306
db_database: "{{ mysql_app_db }}"
db_user: "{{ mysql_app_user }}"
db_pass: "{{ mysql_app_pass }}"