---
- name: install Mysql
  hosts: all
  vars:
    - mysql_root_password: mysql_root_password
    - mysql_app_db: laravel_db
    - mysql_app_user: mysql_user
    - mysql_app_pass: db_password
  tasks:  

    - name: Install Mysql & mysql-python prereq
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'mysql-server', 'python3-pymysql' ]
    
    # Mysql Configuration
    - name: Sets the root password
      mysql_user:
        name: root
        login_user: root
        login_password: "{{ mysql_root_password }}"
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      no_log: false
    
    - name: Removes all anonymous user accounts
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: ''
        host_all: yes
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock
      no_log: false
    
    - name: Removes the MySQL test database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: test
        state: absent
        login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: Creates App Database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_app_db }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: Create App MySQL user and grants access to App DB
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_app_user }}"
        password: "{{ mysql_app_pass }}"
        priv: "{{ mysql_app_db }}.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      no_log: false