---
- name:
  hosts: all
  vars:
  
    http_conf: laravel-app
    http_port: "80" 
    http_host: "{{ ansible_facts.eth0.ipv4.address }}"
    remote_www_root: /var/www
    app_root_dir: laravel
    #http_host: "_"
    document_root: "{{ remote_www_root }}/{{ app_root_dir }}/public"
    
    
  tasks:
  
    - name: Install Nginx
      apt: name=nginx update_cache=yes state=latest
    
    # Nginx Configuration
    - name: Sets Nginx conf file
      template:
        src: "nginx.config.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"
    
    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link
      notify: Reload Nginx
    
    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx
    
    # UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
        
  handlers:
  
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
    
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted    